In [1]:
import pandas as pd

In [3]:
out_dict = {
    "state": [],
    "city": [],
    "area": []
}

In [7]:
df = pd.read_csv('places.csv')

In [8]:
df

     date             place  b   c   d
0  11 Mar  karn;blore;ecity  1  10  20
1  12 Mar         keral;abc  2  11  21
2  13 Mar             delhi  3  12  22
3  14 Mar               efg  4  13  23
4  15 Mar              hjhk  5  14  24

In [29]:
df["state"] = ""
df["city"] = ""
df["area"] = ""

def appl (in_row):
    arr = in_row['place'].split(";")
    
    if len(arr) == 3:
        in_row['state'] = arr[0] 
        in_row['city'] = arr[1] 
        in_row['area'] = arr[2] 

    elif len(arr) == 2:
        in_row['state'] = arr[0] 
        in_row['city'] = arr[1] 
        in_row['area'] = "" 
    
    else:
        in_row['state'] = arr[0] 
        in_row['city'] = "" 
        in_row['area'] = "" 
    return in_row  

df = df.apply(appl, axis=1)

In [30]:
df

     date             place  b   c   d  state   city   area
0  11 Mar  karn;blore;ecity  1  10  20   karn  blore  ecity
1  12 Mar         keral;abc  2  11  21  keral    abc
2  13 Mar             delhi  3  12  22  delhi
3  14 Mar               efg  4  13  23    efg
4  15 Mar              hjhk  5  14  24   hjhk